# =begin
# #Simple Storage Server
#
# #A Simple Storage Server API
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.3.1
#
# =end
#
# require 'spec_helper'
# require 'json'
# require 'support/user_helpers'
#
# # Unit tests for SwaggerClient::FileApi
# # Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# # Please update as you see appropriate
# describe 'FileApi' do
#   before do
#     # run before each test
#     @instance = SwaggerClient::FileApi.new
#   end
#
#   after do
#     # run after each test
#   end
#
#   describe 'test an instance of FileApi' do
#     it 'should create an instance of FileApi' do
#       expect(@instance).to be_instance_of(SwaggerClient::FileApi)
#     end
#   end
#
#   # unit tests for delete_file
#   # Deletes a file
#   #
#   # @param x_session Session token given at login
#   # @param filename name of the file to delete
#   # @param [Hash] opts the optional parameters
#   # @return [nil]
#   describe 'delete_file test' do
#     it "should work" do
#       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
#     end
#   end
#
#   # unit tests for get_file_by_name
#   # download a file
#   # Returns a single file
#   # @param x_session Session token given at login
#   # @param filename name of the file
#   # @param [Hash] opts the optional parameters
#   # @return [File]
#   describe 'get_file_by_name test' do
#     it "should work" do
#       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
#     end
#   end
#
#   # unit tests for list_user_files
#   # List the user&#39;s files
#   #
#   # @param x_session Session token given at login
#   # @param [Hash] opts the optional parameters
#   # @return [Array<String>]
#   describe 'list_user_files test' do
#     it "should work" do
#       create_user_successfully(@valid_user)
#       session_token = login_user_successfully(@valid_user)
#       files = @instance.list_user_files(session_token)
#
#       expect(files).to match_array([])
#     end
#   end
#
#   # unit tests for upload_file
#   # uploads a file
#   #
#   # @param x_session Session token given at login
#   # @param filename name of the file
#   # @param [Hash] opts the optional parameters
#   # @option opts [File] :file file to upload
#   # @return [nil]
#   describe 'upload_file test' do
#     it "should work" do
#       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
#     end
#   end
#
# end
