# coding: utf-8

"""
    Simple Storage Server

    A Simple Storage Server API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.file_api import FileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.file_api.FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Deletes a file  # noqa: E501
        """
        pass

    def test_get_file_by_name(self):
        """Test case for get_file_by_name

        download a file  # noqa: E501
        """
        pass

    def test_list_user_files(self):
        """Test case for list_user_files

        List the user's files  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        uploads a file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
