# coding: utf-8

"""
    Simple Storage Server

    A Simple Storage Server API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.session_token import SessionToken  # noqa: E501
from swagger_client.rest import ApiException


class TestSessionToken(unittest.TestCase):
    """SessionToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionToken(self):
        """Test SessionToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.session_token.SessionToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
